server:
  port: 9002
spring:  application:    name: caidan-user  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercenter?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root  jpa:    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
     
eureka:  client:    service-url:      defaultZone: http://localhost:6868/eureka/
  instance:    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  
      
      