server:
  port: 9004
spring:  application:    name: caidan-webeureka:  client:    service-url:      defaultZone: http://localhost:6868/eureka/
  instance:    prefer-ip-address: true
zuul:  routes:    caidan-user:
      path: /api-user/**
      service-id: caidan-user
    caidan-quartz:
      path: /api-quartz/**
      service-id: caidan-quartz

  
      
      